In [170]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
import time

In [171]:
## ETl project is about test crickrt highest runs in year of 2017 and 2018, url use to get deta for year 2018 and csv for 2017

In [172]:
 url = 'http://stats.espncricinfo.com/ci/engine/records/batting/most_runs_career.html?class=1;id=2018;type=year'

In [173]:
response = requests.get(url)

In [174]:
soup = BeautifulSoup(response.text, 'html.parser')

In [175]:
print(soup.prettify())

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- hostname: web003, edition-view: espncricinfo-en-us, country: unknown, cluster: www, created: 2019-02-25 02:50:06 -->
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://developers.facebook.com/schema/" xmlns:og="http://opengraphprotocol.org/schema/">
 <head>
  <script type="text/javascript">
   var _sf_startpt=(new Date()).getTime()
  </script>
  <meta content="ZxdgH3XglRg0Bsy-Ho2RnO3EE4nRs53FloLS6fkt_nc" name="google-site-verification"/>
  <title>
   2018 Cricket Team Records &amp; Stats | ESPNcricinfo.com
  </title>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
  <meta content="Records,  / , 2018,  / , Test matches,  / , Most runs records, stats, bowling, batting, wicket keeper" name="keywords"/>
  <meta content="Read about Records,  / , 2018,  / , Test matches,  / , Most runs Cricket Team Records only on ESPNcricinfo.com. Check the Stats &amp; Records of Records,  / , 2018,  / , Test matches,  / , Most runs Players in ✓ Wicket keeper ✓ Batting ✓ Bowling" name="description"/>
  <!--[if IE 9]>
<script language="javascript" type="text/javascript">
function fnCreateJumpList(iScenario) {
fnClearJumpList();
window.external.msSiteModeCreateJumpList("Quick Links")
window.external.msSiteModeAddJumpListItem('TCM', 'http://www.espncricinfo.com/ci/content/current/url/784439.html', 'http://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('Betting', 'http://www.espncricinfo.com/ci/content/current/url/701349.html', 'http://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('Both Ends', 'http://www.espncricinfo.com/ci/content/current/url/1094910.html', 'http://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('MATCH DAY', 'http://www.espncricinfo.com/ci/content/current/url/1065560.html', 'http://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('Insights', 'http://www.espncricinfo.com/ci/content/current/url/834953.html', 'http://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('COUNTY 2017', 'http://www.espncricinfo.com/county-cricket-2017/content/current/series/1060993.html', 'http://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('WI v IND', 'http://www.espncricinfo.com/west-indies-v-india-2017/content/current/series/1098203.html', 'http://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('ENG v SA', 'http://www.espncricinfo.com/england-v-south-africa-2017/content/current/series/1031417.html', 'http://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('WWC', 'http://www.espncricinfo.com/icc-womens-world-cup-2017/content/current/series/1085935.html', 'http://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeAddJumpListItem('SL v ZIM', 'http://www.espncricinfo.com/sri-lanka-v-zimbabwe-2017/content/current/series/1104471.html', 'http://a.espncdn.com/espncricinfo/favicon.ico');window.external.msSiteModeShowJumpList();
}
function fnClearJumpList() {
window.external.msSiteModeClearJumplist();
}
</script>

<meta name="msapplication-task" content="name=Live Scores;action-uri=http://www.espncricinfo.com/ci/engine/current/match/scores/live.html;icon-uri=http://a.espncdn.com/espncricinfo/favicon.ico"/>
<meta name="msapplication-task" content="name=Latest News;action-uri=http://www.espncricinfo.com/ci/content/current/story/news.html;icon-uri=http://a.espncdn.com/espncricinfo/favicon.ico"/>
<meta name="msapplication-task" content="name=Fixtures;action-uri=http://www.espncricinfo.com/ci/content/current/match/fixtures/index.html;icon-uri=http://a.espncdn.com/espncricinfo/favicon.ico"/>
<meta name="msapplication-task" content="name=Results;action-uri=http://www.espncricinfo.com/ci/engine/current/match/scores/recent.html;icon-uri=http://a.espncdn.com/espncricinfo/favicon.ico"/>
<meta name="msapplication-task" content="name=Photos;action-uri=http://www.espncricinfo.com/ci/content/current/image/index.html;icon-uri=http://a.espncdn.com/espncricinfo/favicon.ico"/>
<meta name="msapplication-task" content="name=Audio/Video;action-uri=http://www.espncricinfo.com/ci/content/video_audio/index.html;icon-uri=http://a.espncdn.com/espncricinfo/favicon.ico"/>
<script language="javascript" type="text/javascript">
        fnCreateJumpList(2);
</script>
<![endif]-->
  <meta content="index, follow" name="robots"/>
  <meta content="index, follow" name="googlebot"/>
  <meta content="2018 Cricket Team Records &amp; Stats | ESPNcricinfo.com" property="og:title"/>
  <meta content="Read about Records,  / , 2018,  / , Test matches,  / , Most runs Cricket Team Records only on ESPNcricinfo.com. Check the Stats &amp; Records of Records,  / , 2018,  / , Test matches,  / , Most runs Players in ✓ Wicket keeper ✓ Batting ✓ Bowling" property="og:description"/>
  <link href="http://stats.espncricinfo.com/ci/engine/records/batting/most_runs_career.html?class=1&amp;id=2018&amp;type=year" rel="canonical"/>
  <meta content="http://stats.espncricinfo.com/ci/engine/records/batting/most_runs_career.html?class=1&amp;id=2018&amp;type=year" property="og:url"/>
  <meta content="article" property="og:type"/>
  <meta content="507509800,543647230,521294616,502164596,548845180,100000100658108,738070288" property="fb:admins"/>
  <link href="http://i.imgci.com/espncricinfo/facebook.jpg" rel="image_src"/>
  <meta content="http://i.imgci.com/espncricinfo/facebook.jpg" property="og:image"/>
  <meta name="twitter:site" value="@espncricinfo"/>
  <meta name="twitter:creator" value="@espncricinfo"/>
  <meta content="2018 Cricket Team Records &amp; Stats | ESPNcricinfo.com" name="twitter:title"/>
  <meta content="Read about Records,  / , 2018,  / , Test matches,  / , Most runs Cricket Team Records only on ESPNcricinfo.com. Check the Stats &amp; Records of Records,  / , 2018,  / , Test matches,  / , Most runs Players in ✓ Wicket keeper ✓ Batting ✓ Bowling" name="twitter:description"/>
  <meta content="http://i.imgci.com/espncricinfo/twitter.jpg" property="twitter:image:src">
   <link href="http://a.espncdn.com/espncricinfo/favicon.ico" rel="shortcut icon"/>
   <link href="http://a.espncdn.com/espncricinfo/favicon.png" rel="icon" type="image/png"/>
   <link href="http://a.espncdn.com/espncricinfo/favicon.gif" rel="icon" type="image/gif"/>
   <link href="http://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-57x57.min.png" rel="apple-touch-icon"/>
   <link href="http://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-57x57.min.png" rel="apple-touch-icon-precomposed"/>
   <link href="http://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-72x72.min.png" rel="apple-touch-icon-precomposed" sizes="72x72"/>
   <link href="http://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-114x114.min.png" rel="apple-touch-icon-precomposed" sizes="114x114"/>
   <link href="http://a.espncdn.com/wireless/mw5/r1/images/bookmark-icons/espncricinfo_icon-152x152.min.png" rel="apple-touch-icon-precomposed" sizes="152x152"/>
   <meta content="260890547115" property="fb:app_id">
    <meta content="Cricinfo" property="og:site_name">
     <!-- Cricinfo Global News RSS feed link -->
     <link href="/rss/content/story/feeds/0.xml" rel="alternate" title="Global News RSS Feed" type="application/rss+xml">
      <link href="/rss/livescores.xml" rel="alternate" title="Cricinfo live scores RSS feed" type="application/rss+xml">
       <link charset="utf-8" href="http://a.espncdn.com/combiner/c?css=fonts/bentonsans.css,fonts/bentonsansbold.css,fonts/bentonsanslight.css,fonts/bentonsansmedium.css,fonts/bentonsanscond.css,fonts/bentonsanscondbold.css,fonts/bentonsanscondmedium.css" media="screen" rel="stylesheet" type="text/css"/>
       <link charset="utf-8" href="http://i.imgci.com/navigation/cricinfo/ci/assets/css/sub_nav.css?v=1459761501" media="screen" rel="stylesheet" type="text/css"/>
       <link href="http://i.imgci.com/navigation/cricinfo/ci/global.0.0.1.css?1500527079" rel="stylesheet" type="text/css">
        <script language="javascript" type="text/javascript">
         if(navigator.userAgent.indexOf('Linux') != -1) {
		var linux = '/navigation/cricinfo/ci/global_linux.css?1359981014';
		var linuxcss=document.createElement("link");
		linuxcss.setAttribute("rel", "stylesheet");
		linuxcss.setAttribute("type", "text/css");
		linuxcss.setAttribute("href", linux);
		document.getElementsByTagName("head")[0].appendChild(linuxcss);
	}
        </script>
        <script language="javascript" src="http://i.imgci.com/navigation/cricinfo/ci/jquery-1.7.2.min.js" type="text/javascript">
        </script>
        <script language="javascript" src="http://i.imgci.com/navigation/cricinfo/ci/default.js?1444812066" type="text/javascript">
        </script>
        <script src="http://a.espncdn.com/combiner/c?js=jquery-1.7.1.js,plugins/jquery.metadata.js,plugins/jquery.pubsub.r5.js,plugins/ba-debug-0.4.js,espn.l10n.r12.js,espn.core.duo.r55.js,espn.storage.r6.js,espn.geo.r2.js">
        </script>
        <link href="http://i.imgci.com/navigation/cricinfo/ci/vod_player/css/espn-web-player-bundle.1.0.1.css?v=1510209320" rel="stylesheet">
         <!-- VOD Shim starts -->
         <script src="http://a.espncdn.com/prod/scripts/video/2.14.1-5/espn.video.universal.min.js">
         </script>
         <script src="http://i.imgci.com/navigation/cricinfo/ci/vod_player/js/min/video.1.0.0.js">
         </script>
         <!-- VOD Shim ends -->
         <script language="javascript" type="text/javascript">
          if (typeof $ === 'undefined'){
		var $ = jQuery;
	}
	ord=Math.random()*10000000000000000;
	var ad_counter = 1;

	cqanswer = '99';
	location_country = 'unknown';
	location_cluster = 'www';
         </script>
         <script src="http://i.imgci.com/navigation/cricinfo/ci/assets/js/plugins/jquery.cookie-1.4.1.js">
         </script>
         <style type="text/css">
          .video-play-button{background: url(http://img.cricinfo.com/espncricinfo/video/play-icon.png) no-repeat center center;bottom: 0px;left: 0px;position: absolute;right: 0px;text-shadow: none;top: 0px;width: 100%;background-size: 50px auto;opacity: .6;color: transparent;cursor:pointer;}
.video-play-button:hover{opacity: 1;}
         </style>
         <meta content="ESPNcricinfo" name="application-name">
          <meta content="#266ab4" name="msapplication-TileColor"/>
          <meta content="http://i.imgci.com/espncricinfo/6b245241-3938-499c-8c79-9b80f97bed96.png" name="msapplication-TileImage"/>
          <!--Added clevertap code here to avoid adding the code multiple files -->
          <script type="text/javascript">
           window.clevertap = {event:[], profile:[], account:[{"id": "WRK-48Z-445Z"}], notifications:[]};
          </script>
          <!-- Load GPT JavaScript library used by DFP -->
          <script type="text/javascript">
           var googletag = googletag || {};
  googletag.cmd = googletag.cmd || [];
  (function() {
    var gads = document.createElement("script");
    gads.async = true;
    gads.type = "text/javascript";
    var useSSL = true;
    // var useSSL = "https:" == document.location.protocol;
    gads.src = (useSSL ? "https:" : "http:") + "//www.googletagservices.com/tag/js/gpt.js";
    var node =document.getElementsByTagName("script")[0];
    node.parentNode.insertBefore(gads, node);
   })();
          </script>
          <script src="http://a.espncdn.com/combiner/c?js=swfobject/2.2/swfobject.js?minify=false" type="text/javascript">
          </script>
          <style>
           .espni-ad-slot{line-height: 0;}
pre.gpt-debug{padding: 10px; background: burlywood;}
          </style>
          <script type="text/javascript">
           var ad_setting = {"adtar":"","kvbrand":"ci","kvcluster":"www","kvnavtype":"records","kvpt":"stats","kvsite":"stats","networkid":"6444","path":"/6444/espn.cricinfo.com/stats","sp":"cricinfo","template":"desktop","template_type":"non_responsive"}; var __GPTenabled = true;
          </script>
         </meta>
        </link>
       </link>
      </link>
     </link>
    </meta>
   </meta>
  </meta>
 </head>
 <body id="cric_old_template">
  <script type="text/javascript">
   window.espn = window.espn || {};
  espn.isOneSite = true;
  </script>
  <script src="http://cdn.espn.com/core/format/modules/head/i18n?edition-host=espncricinfo.com&amp;type=ext&amp;site=espncricinfo®ion=us&amp;lang=en&amp;build=0.425.7">
  </script>
  <link crossorigin="" href="http://a.espncdn.com" rel="preconnect"/>
  <!--<link rel="stylesheet" href="http://local.espncricinfo.com:8080/static/css/transitional-header-cricinfo.css" />
<link rel="stylesheet" href="/navigation/cricinfo/ci/redesign/css/transitional-header/transitional-header-cricinfo.css">-->
  <link href="http://a.espncdn.com/redesign/0.425.7/css/transitional-header-cricinfo.css" rel="stylesheet">
   <style>
    #global-viewport #header-wrapper{position:relative!important}#global-viewport{font-size:16px!important;font-family:sans-serif!important}body{background:#edeef0!important}#global-viewport .footer{background:0 0;text-transform:initial!important}.global-search .search-results ul a{font-size:12px;line-height:16px}.global-search .search-results ul a b{font-family:BentonSans,-apple-system,Roboto,Helvetica,Arial,sans-serif!important}#global-nav .pillar.editions>div{left:auto!important}.feed-title{line-height:24px!important;text-transform:uppercase;font-family:BentonSans,-apple-system,Roboto,Helvetica,Arial,sans-serif!important}.feed-title.favorites span{color:#06c;cursor:pointer;display:block;font-weight:400;line-height:13px;position:absolute;right:10px;text-transform:none;top:5px}#global-scoreboard-trigger+.alert{padding:12px 35px 12px 18px;font-size:12px}.hidden{display:none!important}@media screen and (min-width:768px){.scores-link-alert{display:none!important}}@media screen and (min-width:1024px){.global-user .current-favorites{padding:0 10px 34px 20px!important}}.lightbox.favorites-mgmt{height:518px;margin-left:-378px;width:756px}.lightbox-container .lightbox.favorites-mgmt{padding-top:0}@media screen and (min-width:768px){.lightbox-container .lightbox.favorites-mgmt{height:370px;width:700px}}.lightbox-container .lightbox.favorites-mgmt .btn-close:before{font-size:24px;line-height:24px}@media screen and (min-width:1260px){.lightbox-container .lightbox.favorites-mgmt iframe{width:1260px}}@media screen and (min-width:1024px) and (max-width:1259px){.lightbox-container .lightbox.favorites-mgmt iframe{width:1024px}}@media screen and (min-width:1px) and (max-width:1023px){.lightbox-container .lightbox.favorites-mgmt{margin-left:-338px;-webkit-overflow-scrolling:touch;width:676px}.lightbox-container .lightbox.favorites-mgmt iframe{width:768px}}@media screen and (max-width:767px){.lightbox-container .lightbox.favorites-mgmt{height:inherit;margin-left:0;width:100%}.lightbox-container .lightbox.favorites-mgmt iframe{width:100%}}.search_results__header{border-bottom:1px dotted #dcdddf!important;font-size:13px!important;font-weight:700!important;line-height:16px!important;padding:5px 5px 5px 8px!important;margin:0 12px!important}.search_results__suggestions .search_results__item{font-size:12px!important}.search_results__details {font-weight: 600 !important;line-height: 1.2 !important;}#global-search footer{padding:0 !important;}
   </style>
   <style type="text/css">
    html{
    background: none !important;
  }
  #global-viewport #global-nav .more-espn ul.featured {
    margin: 0 !important;
    padding: 0 15px !important;
    width: 100% !important;
    background: transparent !important;
    display: block;
  }
  #ciHomeLeaderboard{
    margin-top:10px;
  }
   </style>
   <script src="http://a.espncdn.com/redesign/0.425.7/js/espn-head.js">
   </script>
   <div class="espncricinfo transitional-header legacy-pages" data-behavior="global_nav_condensed global_nav_full" id="global-viewport">
    <nav data-loadtype="client" id="global-nav-mobile">
    </nav>
    <div class="menu-overlay-primary">
    </div>
    <div class="hidden-print" data-behavior="global_header" id="header-wrapper">
     <header class="espncricinfo-en user-account-management has-search" id="global-header">
      <div class="menu-overlay-secondary">
      </div>
      <div class="container">
       <a data-route="false" href="#" id="global-nav-mobile-trigger">
        <span>
         Menu
        </span>
       </a>
       <h1>
        <a href="/" name="&amp;lpos=sitenavdefault&amp;lid=sitenav_main-logo">
         ESPN
        </a>
       </h1>
       <ul class="tools">
        <li class="search">
         <a class="icon-font-after icon-search-solid-after" href="#" id="global-search-trigger">
         </a>
         <div class="global-search" id="global-search">
          <input class="search-box" placeholder="Search Sports, Teams or Players..." type="text"/>
          <input class="btn-search" type="submit"/>
         </div>
        </li>
        <li class="user" data-behavior="favorites_mgmt">
        </li>
        <li>
         <a data-route="false" href="#" id="global-scoreboard-trigger">
          Scores
         </a>
         <div class="hidden scores-link-alert scores-link-alert alert alert_button--close icon-font-after icon-close-solid-after" data-behavior="scores_link_alert">
          All cricket scores, fixtures and results here.
         </div>
        </li>
       </ul>
      </div>
     </header>
    </div>
   </div>
  </link>
 </body>
</html>
<nav data-loadtype="server" id="global-nav">
 <ul itemscope="">
 </ul>
</nav>
<nav data-loadtype="server" id="global-nav-secondary">
 <div class="global-nav-container">
 </div>
</nav>
<!--  <div id="ciHomeMastContainer">


 </div> -->
<div class="subnav-wrap sub-nav ">
 <div class="row">
  <div class="large-20 sub-nav-wrap" id="sub-nav-wrap">
   <div class="icc-home">
    <a href="/ci/engine/records/index.html">
     Records / 2018 / Test matches / Most runs
    </a>
   </div>
   <ul class="subnav_tier1 subnav-item-wrap" data-role="none" id="subnav_tier1">
    <li>
     <a href="/ci/engine/stats/index.html" name="&amp;lpos=quicklink_Statsguru">
      Statsguru
     </a>
    </li>
    <li>
     <a href="/ci/engine/current/records/index.html" name="&amp;lpos=quicklink_Records">
      Records
     </a>
     <div class="dd_wrap">
      <ul class="subnav_grp">
       <li class="subnav_grpitm">
        <ul class="subnav_tire2">
         <li class="sub_nav_item">
          <a href="/ci/engine/current/records/index.html?id=2019;type=year" name="&amp;lpos=quicklink_2019">
           2019
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="/ci/engine/current/records/index.html?id=2018;type=year" name="&amp;lpos=quicklink_2018">
           2018
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="/ci/engine/current/records/index.html?id=2017;type=year" name="&amp;lpos=quicklink_2017">
           2017
          </a>
         </li>
         <li class="sub_nav_item">
          <a href="/ci/engine/current/records/index.html?id=2016;type=year" name="&amp;lpos=quicklink_2016">
           2016
          </a>
         </li>
        </ul>
       </li>
      </ul>
     </div>
    </li>
    <li>
     <a href="/ci/content/story/genre.html?genre=6" name="&amp;lpos=quicklink_Ask Steven">
      Ask Steven
     </a>
    </li>
    <li>
     <a href="/magazine/content/story/magazine/author.html?author=29;genre=12" name="&amp;lpos=quicklink_Numbers Game">
      Numbers Game
     </a>
    </li>
    <li>
     <a href="/ci/engine/records/index.html?id=12;type=trophy" name="&amp;lpos=quicklink_World Cup">
      World Cup
     </a>
     <div class="dd_wrap">
      <ul class="subnav_grp">
       <li class="subnav_grpitm">

In [176]:
results = soup.find_all("tr",class_="data1")
results

[<tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 1"><a class="data-link" href="/ci/content/player/253802.html">V Kohli</a> (INDIA)</td>
 <td class="padAst" nowrap="nowrap">13</td>
 <td nowrap="nowrap">24</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>1322</b></td>
 <td class="padAst" nowrap="nowrap">153</td>
 <td nowrap="nowrap">55.08</td>
 <td nowrap="nowrap">2433</td>
 <td nowrap="nowrap">54.33</td>
 <td nowrap="nowrap">5</td>
 <td nowrap="nowrap">5</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">144</td>
 <td nowrap="nowrap">2</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 2"><a class="data-link" href="/ci/content/player/629074.html">BKG Mendis</a> (SL)</td>
 <td class="padAst" nowrap="nowrap">12</td>
 <td nowrap="nowrap">23</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap"><b>1023</b></td>
 <td class="padAst" nowrap="nowrap">196</td>
 <td nowrap="nowrap">46.50</td>
 <td nowrap="nowrap">1872</td>
 <td nowrap="nowrap">54.64</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">4</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">126</td>
 <td nowrap="nowrap">9</td>
 </tr>, <tr class="data1" data-days="737389">
 <td class="left" nowrap="nowrap" title="record rank: 3"><a class="data-link" href="/ci/content/player/303669.html">JE Root</a> (ENG)</td>
 <td class="padAst" nowrap="nowrap">13</td>
 <td nowrap="nowrap">24</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap"><b>948</b></td>
 <td class="padAst" nowrap="nowrap">125</td>
 <td nowrap="nowrap">41.21</td>
 <td nowrap="nowrap">1782</td>
 <td nowrap="nowrap">53.19</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">6</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">92</td>
 <td nowrap="nowrap">3</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 4"><a class="data-link" href="/ci/content/player/32540.html">CA Pujara</a> (INDIA)</td>
 <td class="padAst" nowrap="nowrap">13</td>
 <td nowrap="nowrap">23</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap"><b>837</b></td>
 <td nowrap="nowrap">132*</td>
 <td nowrap="nowrap">38.04</td>
 <td nowrap="nowrap">2176</td>
 <td nowrap="nowrap">38.46</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">4</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">98</td>
 <td nowrap="nowrap">2</td>
 </tr>, <tr class="data1" data-days="737389">
 <td class="left" nowrap="nowrap" title="record rank: 5"><a class="data-link" href="/ci/content/player/308967.html">JC Buttler</a> (ENG)</td>
 <td class="padAst" nowrap="nowrap">10</td>
 <td nowrap="nowrap">18</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap"><b>760</b></td>
 <td class="padAst" nowrap="nowrap">106</td>
 <td nowrap="nowrap">44.70</td>
 <td nowrap="nowrap">1116</td>
 <td nowrap="nowrap">68.10</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">6</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">84</td>
 <td nowrap="nowrap">7</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 6"><a class="data-link" href="/ci/content/player/227772.html">FDM Karunaratne</a> (SL)</td>
 <td class="padAst" nowrap="nowrap">9</td>
 <td nowrap="nowrap">17</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap"><b>743</b></td>
 <td nowrap="nowrap">158*</td>
 <td nowrap="nowrap">46.43</td>
 <td nowrap="nowrap">1312</td>
 <td nowrap="nowrap">56.63</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">7</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">71</td>
 <td nowrap="nowrap">1</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 7"><a class="data-link" href="/ci/content/player/215155.html">UT Khawaja</a> (AUS)</td>
 <td class="padAst" nowrap="nowrap">10</td>
 <td nowrap="nowrap">18</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>732</b></td>
 <td class="padAst" nowrap="nowrap">171</td>
 <td nowrap="nowrap">40.66</td>
 <td nowrap="nowrap">1689</td>
 <td nowrap="nowrap">43.33</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">4</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap">78</td>
 <td nowrap="nowrap">2</td>
 </tr>, <tr class="data1" data-days="737395">
 <td class="left" nowrap="nowrap" title="record rank: 8"><a class="data-link" href="/ci/content/player/373696.html">Mominul Haque</a> (BDESH)</td>
 <td class="padAst" nowrap="nowrap">8</td>
 <td nowrap="nowrap">15</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>673</b></td>
 <td class="padAst" nowrap="nowrap">176</td>
 <td nowrap="nowrap">44.86</td>
 <td nowrap="nowrap">1015</td>
 <td nowrap="nowrap">66.30</td>
 <td nowrap="nowrap">4</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">63</td>
 <td nowrap="nowrap">4</td>
 </tr>, <tr class="data1" data-days="737421">
 <td class="left" nowrap="nowrap" title="record rank: 9"><a class="data-link" href="/ci/content/player/600498.html">AK Markram</a> (SA)</td>
 <td class="padAst" nowrap="nowrap">10</td>
 <td nowrap="nowrap">20</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>672</b></td>
 <td class="padAst" nowrap="nowrap">152</td>
 <td nowrap="nowrap">33.60</td>
 <td nowrap="nowrap">1099</td>
 <td nowrap="nowrap">61.14</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">90</td>
 <td nowrap="nowrap">3</td>
 </tr>, <tr class="data1" data-days="737421">
 <td class="left" nowrap="nowrap" title="record rank: 10"><a class="data-link" href="/ci/content/player/230852.html">D Elgar</a> (SA)</td>
 <td class="padAst" nowrap="nowrap">10</td>
 <td nowrap="nowrap">20</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap"><b>661</b></td>
 <td nowrap="nowrap">141*</td>
 <td nowrap="nowrap">36.72</td>
 <td nowrap="nowrap">1697</td>
 <td nowrap="nowrap">38.95</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">5</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">87</td>
 <td nowrap="nowrap">4</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 11"><a class="data-link" href="/ci/content/player/388802.html">TWM Latham</a> (NZ)</td>
 <td class="padAst" nowrap="nowrap">7</td>
 <td nowrap="nowrap">12</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap"><b>658</b></td>
 <td nowrap="nowrap">264*</td>
 <td nowrap="nowrap">59.81</td>
 <td nowrap="nowrap">1528</td>
 <td nowrap="nowrap">43.06</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">62</td>
 <td nowrap="nowrap">2</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 11"><a class="data-link" href="/ci/content/player/539511.html">HM Nicholls</a> (NZ)</td>
 <td class="padAst" nowrap="nowrap">7</td>
 <td nowrap="nowrap">12</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap"><b>658</b></td>
 <td nowrap="nowrap">162*</td>
 <td nowrap="nowrap">73.11</td>
 <td nowrap="nowrap">1352</td>
 <td nowrap="nowrap">48.66</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">67</td>
 <td nowrap="nowrap">1</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 13"><a class="data-link" href="/ci/content/player/277906.html">KS Williamson</a> (NZ)</td>
 <td class="padAst" nowrap="nowrap">7</td>
 <td nowrap="nowrap">12</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap"><b>651</b></td>
 <td class="padAst" nowrap="nowrap">139</td>
 <td nowrap="nowrap">59.18</td>
 <td nowrap="nowrap">1195</td>
 <td nowrap="nowrap">54.47</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">61</td>
 <td nowrap="nowrap">1</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 14"><a class="data-link" href="/ci/content/player/277916.html">AM Rahane</a> (INDIA)</td>
 <td class="padAst" nowrap="nowrap">12</td>
 <td nowrap="nowrap">21</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>644</b></td>
 <td class="padAst" nowrap="nowrap">81</td>
 <td nowrap="nowrap">30.66</td>
 <td nowrap="nowrap">1462</td>
 <td nowrap="nowrap">44.04</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap">5</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">65</td>
 <td nowrap="nowrap">3</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 15"><a class="data-link" href="/ci/content/player/49764.html">AD Mathews</a> (SL)</td>
 <td class="padAst" nowrap="nowrap">8</td>
 <td nowrap="nowrap">16</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap"><b>640</b></td>
 <td nowrap="nowrap">120*</td>
 <td nowrap="nowrap">49.23</td>
 <td nowrap="nowrap">1389</td>
 <td nowrap="nowrap">46.07</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">5</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap">56</td>
 <td nowrap="nowrap">2</td>
 </tr>, <tr class="data1" data-days="737152">
 <td class="left" nowrap="nowrap" title="record rank: 16"><a class="data-link" href="/ci/content/player/44936.html">AB de Villiers</a> (SA)</td>
 <td class="padAst" nowrap="nowrap">7</td>
 <td nowrap="nowrap">14</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap"><b>638</b></td>
 <td nowrap="nowrap">126*</td>
 <td nowrap="nowrap">53.16</td>
 <td nowrap="nowrap">990</td>
 <td nowrap="nowrap">64.44</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">6</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">86</td>
 <td nowrap="nowrap">6</td>
 </tr>, <tr class="data1" data-days="737421">
 <td class="left" nowrap="nowrap" title="record rank: 17"><a class="data-link" href="/ci/content/player/348144.html">Babar Azam</a> (PAK)</td>
 <td class="padAst" nowrap="nowrap">8</td>
 <td nowrap="nowrap">14</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap"><b>616</b></td>
 <td nowrap="nowrap">127*</td>
 <td nowrap="nowrap">56.00</td>
 <td nowrap="nowrap">1131</td>
 <td nowrap="nowrap">54.46</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">6</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">69</td>
 <td nowrap="nowrap">6</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 17"><a class="data-link" href="/ci/content/player/237310.html">ARS Silva</a> (SL)</td>
 <td class="padAst" nowrap="nowrap">10</td>
 <td nowrap="nowrap">19</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap"><b>616</b></td>
 <td class="padAst" nowrap="nowrap">109</td>
 <td nowrap="nowrap">36.23</td>
 <td nowrap="nowrap">1477</td>
 <td nowrap="nowrap">41.70</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">4</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">47</td>
 <td nowrap="nowrap">3</td>
 </tr>, <tr class="data1" data-days="737389">
 <td class="left" nowrap="nowrap" title="record rank: 19"><a class="data-link" href="/ci/content/player/297433.html">JM Bairstow</a> (ENG)</td>
 <td class="padAst" nowrap="nowrap">11</td>
 <td nowrap="nowrap">20</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>609</b></td>
 <td class="padAst" nowrap="nowrap">110</td>
 <td nowrap="nowrap">30.45</td>
 <td nowrap="nowrap">1138</td>
 <td nowrap="nowrap">53.51</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">5</td>
 <td nowrap="nowrap">75</td>
 <td nowrap="nowrap">2</td>
 </tr>, <tr class="data1" data-days="737400">
 <td class="left" nowrap="nowrap" title="record rank: 20"><a class="data-link" href="/ci/content/player/318788.html">Haris Sohail</a> (PAK)</td>
 <td class="padAst" nowrap="nowrap">8</td>
 <td nowrap="nowrap">15</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap"><b>550</b></td>
 <td class="padAst" nowrap="nowrap">147</td>
 <td nowrap="nowrap">39.28</td>
 <td nowrap="nowrap">1274</td>
 <td nowrap="nowrap">43.17</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">49</td>
 <td nowrap="nowrap">6</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 21"><a class="data-link" href="/ci/content/player/931581.html">RR Pant</a> (INDIA)</td>
 <td class="padAst" nowrap="nowrap">8</td>
 <td nowrap="nowrap">14</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>537</b></td>
 <td class="padAst" nowrap="nowrap">114</td>
 <td nowrap="nowrap">38.35</td>
 <td nowrap="nowrap">754</td>
 <td nowrap="nowrap">71.22</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">55</td>
 <td nowrap="nowrap">16</td>
 </tr>, <tr class="data1" data-days="737389">
 <td class="left" nowrap="nowrap" title="record rank: 21"><a class="data-link" href="/ci/content/player/311158.html">BA Stokes</a> (ENG)</td>
 <td class="padAst" nowrap="nowrap">10</td>
 <td nowrap="nowrap">20</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>537</b></td>
 <td class="padAst" nowrap="nowrap">66</td>
 <td nowrap="nowrap">26.85</td>
 <td nowrap="nowrap">1165</td>
 <td nowrap="nowrap">46.09</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap">4</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">57</td>
 <td nowrap="nowrap">7</td>
 </tr>, <tr class="data1" data-days="737421">
 <td class="left" nowrap="nowrap" title="record rank: 23"><a class="data-link" href="/ci/content/player/316397.html">Asad Shafiq</a> (PAK)</td>
 <td class="padAst" nowrap="nowrap">9</td>
 <td nowrap="nowrap">16</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>536</b></td>
 <td class="padAst" nowrap="nowrap">104</td>
 <td nowrap="nowrap">33.50</td>
 <td nowrap="nowrap">1094</td>
 <td nowrap="nowrap">48.99</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">60</td>
 <td nowrap="nowrap">4</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 24"><a class="data-link" href="/ci/content/player/429754.html">N Dickwella</a> (SL)</td>
 <td class="padAst" nowrap="nowrap">12</td>
 <td nowrap="nowrap">22</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap"><b>519</b></td>
 <td nowrap="nowrap">80*</td>
 <td nowrap="nowrap">25.95</td>
 <td nowrap="nowrap">782</td>
 <td nowrap="nowrap">66.36</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap">60</td>
 <td nowrap="nowrap">0</td>
 </tr>, <tr class="data1" data-days="737421">
 <td class="left" nowrap="nowrap" title="record rank: 25"><a class="data-link" href="/ci/content/player/39037.html">Azhar Ali</a> (PAK)</td>
 <td class="padAst" nowrap="nowrap">9</td>
 <td nowrap="nowrap">17</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>517</b></td>
 <td class="padAst" nowrap="nowrap">134</td>
 <td nowrap="nowrap">30.41</td>
 <td nowrap="nowrap">1296</td>
 <td nowrap="nowrap">39.89</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">4</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">50</td>
 <td nowrap="nowrap">1</td>
 </tr>, <tr class="data1" data-days="737313">
 <td class="left" nowrap="nowrap" title="record rank: 26"><a class="data-link" href="/ci/content/player/11728.html">AN Cook</a> (ENG)</td>
 <td class="padAst" nowrap="nowrap">10</td>
 <td nowrap="nowrap">18</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>516</b></td>
 <td class="padAst" nowrap="nowrap">147</td>
 <td nowrap="nowrap">28.66</td>
 <td nowrap="nowrap">1171</td>
 <td nowrap="nowrap">44.06</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">65</td>
 <td nowrap="nowrap">0</td>
 </tr>, <tr class="data1" data-days="737421">
 <td class="left" nowrap="nowrap" title="record rank: 27"><a class="data-link" href="/ci/content/player/43906.html">HM Amla</a> (SA)</td>
 <td class="padAst" nowrap="nowrap">10</td>
 <td nowrap="nowrap">20</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap"><b>510</b></td>
 <td class="padAst" nowrap="nowrap">82</td>
 <td nowrap="nowrap">26.84</td>
 <td nowrap="nowrap">1235</td>
 <td nowrap="nowrap">41.29</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap">5</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">64</td>
 <td nowrap="nowrap">0</td>
 </tr>, <tr class="data1" data-days="737412">
 <td class="left" nowrap="nowrap" title="record rank: 28"><a class="data-link" href="/ci/content/player/465793.html">DM de Silva</a> (SL)</td>
 <td class="padAst" nowrap="nowrap">10</td>
 <td nowrap="nowrap">19</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>509</b></td>
 <td class="padAst" nowrap="nowrap">173</td>
 <td nowrap="nowrap">26.78</td>
 <td nowrap="nowrap">858</td>
 <td nowrap="nowrap">59.32</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">58</td>
 <td nowrap="nowrap">4</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 29"><a class="data-link" href="/ci/content/player/7252.html">TD Paine</a> (AUS)</td>
 <td class="padAst" nowrap="nowrap">10</td>
 <td nowrap="nowrap">19</td>
 <td nowrap="nowrap">5</td>
 <td nowrap="nowrap"><b>493</b></td>
 <td class="padAst" nowrap="nowrap">62</td>
 <td nowrap="nowrap">35.21</td>
 <td nowrap="nowrap">1191</td>
 <td nowrap="nowrap">41.39</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">50</td>
 <td nowrap="nowrap">2</td>
 </tr>, <tr class="data1" data-days="737423">
 <td class="left" nowrap="nowrap" title="record rank: 30"><a class="data-link" href="/ci/content/player/6683.html">SE Marsh</a> (AUS)</td>
 <td class="padAst" nowrap="nowrap">10</td>
 <td nowrap="nowrap">19</td>
 <td nowrap="nowrap">0</td>
 <td nowrap="nowrap"><b>492</b></td>
 <td class="padAst" nowrap="nowrap">156</td>
 <td nowrap="nowrap">25.89</td>
 <td nowrap="nowrap">1171</td>
 <td nowrap="nowrap">42.01</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">57</td>
 <td nowrap="nowrap">1</td>
 </tr>, <tr class="data1" data-days="737395">
 <td class="left" nowrap="nowrap" title="record rank: 31"><a class="data-link" href="/ci/content/player/56029.html">Mushfiqur Rahim</a> (BDESH)</td>
 <td class="padAst" nowrap="nowrap">8</td>
 <td nowrap="nowrap">15</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap"><b>490</b></td>
 <td nowrap="nowrap">219*</td>
 <td nowrap="nowrap">35.00</td>
 <td nowrap="nowrap">995</td>
 <td nowrap="nowrap">49.24</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">53</td>
 <td nowrap="nowrap">1</td>
 </tr>, <tr class="data1" data-days="737395">
 <td class="left" nowrap="nowrap" title="record rank: 32"><a class="data-link" href="/ci/content/player/56025.html">Mahmudullah</a> (BDESH)</td>
 <td class="padAst" nowrap="nowrap">8</td>
 <td nowrap="nowrap">15</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap"><b>476</b></td>
 <td class="padAst" nowrap="nowrap">136</td>
 <td nowrap="nowrap">39.66</td>
 <td nowrap="nowrap">870</td>
 <td nowrap="nowrap">54.71</td>
 <td nowrap="nowrap">2</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">33</td>
 <td nowrap="nowrap">5</td>
 </tr>, <tr class="data1" data-days="737395">
 <td class="left" nowrap="nowrap" title="record rank: 33"><a class="data-link" href="/ci/content/player/431905.html">SO Dowrich</a> (WI)</td>
 <td class="padAst" nowrap="nowrap">9</td>
 <td nowrap="nowrap">17</td>
 <td nowrap="nowrap">4</td>
 <td nowrap="nowrap"><b>474</b></td>
 <td nowrap="nowrap">125*</td>
 <td nowrap="nowrap">36.46</td>
 <td nowrap="nowrap">1099</td>
 <td nowrap="nowrap">43.13</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">3</td>
 <td nowrap="nowrap">1</td>
 <td nowrap="nowrap">44</td>
 <td nowrap="nowrap">5</td>
 </tr>, <tr class="data1" data-days="737411">

In [177]:
for result in results:
    name = result.find("td").text
    
    print(name)

V Kohli (INDIA)
BKG Mendis (SL)
JE Root (ENG)
CA Pujara (INDIA)
JC Buttler (ENG)
FDM Karunaratne (SL)
UT Khawaja (AUS)
Mominul Haque (BDESH)
AK Markram (SA)
D Elgar (SA)
TWM Latham (NZ)
HM Nicholls (NZ)
KS Williamson (NZ)
AM Rahane (INDIA)
AD Mathews (SL)
AB de Villiers (SA)
Babar Azam (PAK)
ARS Silva (SL)
JM Bairstow (ENG)
Haris Sohail (PAK)
RR Pant (INDIA)
BA Stokes (ENG)
Asad Shafiq (PAK)
N Dickwella (SL)
Azhar Ali (PAK)
AN Cook (ENG)
HM Amla (SA)
DM de Silva (SL)
TD Paine (AUS)
SE Marsh (AUS)
Mushfiqur Rahim (BDESH)
Mahmudullah (BDESH)
SO Dowrich (WI)
KL Rahul (INDIA)
F du Plessis (SA)
LD Chandimal (SL)
KK Jennings (ENG)
SM Curran (ENG)
RL Chase (WI)
Q de Kock (SA)
Imam-ul-Haq (PAK)
KC Brathwaite (WI)
KOA Powell (WI)
SO Hetmyer (WI)
BJ Watling (NZ)
HH Pandya (INDIA)
SD Hope (WI)
TM Head (AUS)
Sarfaraz Ahmed (PAK)
JO Holder (WI)

In [178]:
for result in results:
    name = result.find("td").text
    matches = result.find("td",  class_="padAst").text
   
    print(name)
    print(matches)

V Kohli (INDIA)
13
BKG Mendis (SL)
12
JE Root (ENG)
13
CA Pujara (INDIA)
13
JC Buttler (ENG)
10
FDM Karunaratne (SL)
9
UT Khawaja (AUS)
10
Mominul Haque (BDESH)
8
AK Markram (SA)
10
D Elgar (SA)
10
TWM Latham (NZ)
7
HM Nicholls (NZ)
7
KS Williamson (NZ)
7
AM Rahane (INDIA)
12
AD Mathews (SL)
8
AB de Villiers (SA)
7
Babar Azam (PAK)
8
ARS Silva (SL)
10
JM Bairstow (ENG)
11
Haris Sohail (PAK)
8
RR Pant (INDIA)
8
BA Stokes (ENG)
10
Asad Shafiq (PAK)
9
N Dickwella (SL)
12
Azhar Ali (PAK)
9
AN Cook (ENG)
10
HM Amla (SA)
10
DM de Silva (SL)
10
TD Paine (AUS)
10
SE Marsh (AUS)
10
Mushfiqur Rahim (BDESH)
8
Mahmudullah (BDESH)
8
SO Dowrich (WI)
9
KL Rahul (INDIA)
12
F du Plessis (SA)
10
LD Chandimal (SL)
7
KK Jennings (ENG)
9
SM Curran (ENG)
7
RL Chase (WI)
9
Q de Kock (SA)
10
Imam-ul-Haq (PAK)
8
KC Brathwaite (WI)
9
KOA Powell (WI)
9
SO Hetmyer (WI)
5
BJ Watling (NZ)
7
HH Pandya (INDIA)
8
SD Hope (WI)
9
TM Head (AUS)
5
Sarfaraz Ahmed (PAK)
9
JO Holder (WI)
6

In [179]:
runs2018 = pd.read_html(url)
runs2018

[                     Player  Mat  Inns  NO  Runs    HS    Ave    BF     SR  \
 0           V Kohli (INDIA)   13    24   0  1322   153  55.08  2433  54.33
 1           BKG Mendis (SL)   12    23   1  1023   196  46.50  1872  54.64
 2             JE Root (ENG)   13    24   1   948   125  41.21  1782  53.19
 3         CA Pujara (INDIA)   13    23   1   837  132*  38.04  2176  38.46
 4          JC Buttler (ENG)   10    18   1   760   106  44.70  1116  68.10
 5      FDM Karunaratne (SL)    9    17   1   743  158*  46.43  1312  56.63
 6          UT Khawaja (AUS)   10    18   0   732   171  40.66  1689  43.33
 7     Mominul Haque (BDESH)    8    15   0   673   176  44.86  1015  66.30
 8           AK Markram (SA)   10    20   0   672   152  33.60  1099  61.14
 9              D Elgar (SA)   10    20   2   661  141*  36.72  1697  38.95
 10          TWM Latham (NZ)    7    12   1   658  264*  59.81  1528  43.06
 11         HM Nicholls (NZ)    7    12   3   658  162*  73.11  1352  48.66
 12       KS Williamson (NZ)    7    12   1   651   139  59.18  1195  54.47
 13        AM Rahane (INDIA)   12    21   0   644    81  30.66  1462  44.04
 14          AD Mathews (SL)    8    16   3   640  120*  49.23  1389  46.07
 15      AB de Villiers (SA)    7    14   2   638  126*  53.16   990  64.44
 16         Babar Azam (PAK)    8    14   3   616  127*  56.00  1131  54.46
 17           ARS Silva (SL)   10    19   2   616   109  36.23  1477  41.70
 18        JM Bairstow (ENG)   11    20   0   609   110  30.45  1138  53.51
 19       Haris Sohail (PAK)    8    15   1   550   147  39.28  1274  43.17
 20          RR Pant (INDIA)    8    14   0   537   114  38.35   754  71.22
 21          BA Stokes (ENG)   10    20   0   537    66  26.85  1165  46.09
 22        Asad Shafiq (PAK)    9    16   0   536   104  33.50  1094  48.99
 23         N Dickwella (SL)   12    22   2   519   80*  25.95   782  66.36
 24          Azhar Ali (PAK)    9    17   0   517   134  30.41  1296  39.89
 25            AN Cook (ENG)   10    18   0   516   147  28.66  1171  44.06
 26             HM Amla (SA)   10    20   1   510    82  26.84  1235  41.29
 27         DM de Silva (SL)   10    19   0   509   173  26.78   858  59.32
 28           TD Paine (AUS)   10    19   5   493    62  35.21  1191  41.39
 29           SE Marsh (AUS)   10    19   0   492   156  25.89  1171  42.01
 30  Mushfiqur Rahim (BDESH)    8    15   1   490  219*  35.00   995  49.24
 31      Mahmudullah (BDESH)    8    15   3   476   136  39.66   870  54.71
 32          SO Dowrich (WI)    9    17   4   474  125*  36.46  1099  43.13
 33         KL Rahul (INDIA)   12    22   1   468   149  22.28   793  59.01
 34        F du Plessis (SA)   10    20   1   463   120  24.36   875  52.91
 35        LD Chandimal (SL)    7    12   1   448  119*  40.72  1096  40.87
 36        KK Jennings (ENG)    9    16   1   425  146*  28.33   893  47.59
 37          SM Curran (ENG)    7    12   1   404    78  36.72   698  57.87
 38            RL Chase (WI)    9    17   0   396   106  23.29   759  52.17
 39           Q de Kock (SA)   10    18   0   392    83  21.77   579  67.70
 40        Imam-ul-Haq (PAK)    8    15   2   391    76  30.07   813  48.09
 41       KC Brathwaite (WI)    9    17   1   391   121  24.43  1129  34.63
 42          KOA Powell (WI)    9    17   0   391    88  23.00   591  66.15
 43          SO Hetmyer (WI)    5    10   0   376    93  37.60   449  83.74
 44          BJ Watling (NZ)    7    11   1   355    85  35.50   950  37.36
 45        HH Pandya (INDIA)    8    15   1   354    93  25.28   555  63.78
 46             SD Hope (WI)    9    17   0   344    67  20.23   780  44.10
 47            TM Head (AUS)    5    10   0   339    72  33.90   757  44.78
 48     Sarfaraz Ahmed (PAK)    9    15   1   337    94  24.07   545  61.83
 49           JO Holder (WI)    6    11   2   336    74  37.33   556  60.43

     100  50  0   4s  6s
 0     5   5  2  144   2
 1     3   4  1  126   9
 2     2   6  2   92   3
 3     3   4  3   98   2
 4     1   6  2   84   7
 5     1   7  2   71   1
 6     2   4  0   78   2
 7     4   0  3   63   4
 8     2   2  3   90   3
 9     1   5  2   87   4
 10    2   2  2   62   2
 11    3   3  2   67   1
 12    2   3  1   61   1
 13    0   5  1   65   3
 14    1   5  0   56   2
 15    1   6  1   86   6
 16    1   6  1   69   6
 17    1   4  1   47   3
 18    2   2  5   75   2
 19    2   0  1   49   6
 20    1   2  1   55  16
 21    0   4  2   57   7
 22    1   3  2   60   4
 23    0   3  0   60   0
 24    1   4  1   50   1
 25    1   2  1   65   0
 26    0   5  2   64   0
 27    1   3  3   58   4
 28    0   2  1   50   2
 29    1   1  2   57   1
 30    1   1  1   53   1
 31    2   1  3   33   5
 32    1   3  1   44   5
 33    1   1  4   60   3
 34    1   2  4   65   4
 35    1   2  1   33   1
 36    1   0  1   41   0
 37    0   3  2   38  14
 38    1   1  2   41   2
 39    0   2  2   51   1
 40    0   3  2   48   3
 41    2   1  2   35   0
 42    0   2  2   43   8
 43    0   3  0   29  17
 44    0   3  2   35   1
 45    0   3  2   52   2
 46    0   1  1   35   3
 47    0   3  1   30   0
 48    0   2  2   29   1
 49    0   2  0   39   6  ,
                                                    0
 0  Records includes the following current or rece...
 1  Australia v India at Melbourne, 3rd Test, Dec ...
 2  New Zealand v Sri Lanka at Christchurch, 2nd T...
 3  South Africa v Pakistan at Centurion, 1st Test...]

In [180]:
df = runs2018[0]
df['Year'] = '2018'
df.head()

,Player,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Year
0,V Kohli (INDIA),13,24,0,1322,153,55.08,2433,54.33,5,5,2,144,2,2018
1,BKG Mendis (SL),12,23,1,1023,196,46.50,1872,54.64,3,4,1,126,9,2018
2,JE Root (ENG),13,24,1,948,125,41.21,1782,53.19,2,6,2,92,3,2018
3,CA Pujara (INDIA),13,23,1,837,132*,38.04,2176,38.46,3,4,3,98,2,2018
4,JC Buttler (ENG),10,18,1,760,106,44.70,1116,68.10,1,6,2,84,7,2018

In [181]:
runs2017 = "./2017_runs.csv"

In [182]:
df = pd.read_csv(runs2017)
df['Year'] ='2017'
df.head()

,Player,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s,Year
0,SPD Smith (AUS),11,20,3,1305,239,76.76,2573,50.71,6,3,0,140,2,2017
1,CA Pujara (INDIA),11,18,1,1140,202,67.05,2484,45.89,4,5,1,115,2,2017
2,D Elgar (SA),12,21,0,1128,199,53.71,2218,50.85,5,4,1,143,3,2017
3,V Kohli (INDIA),10,16,2,1059,243,75.64,1389,76.24,5,1,2,97,6,2017
4,FDM Karunaratne (SL),13,26,0,1031,196,39.65,2304,44.74,3,4,2,91,2,2017